### ISSUE TITLE
Add Hooks to run custom steps pre/post each action

### ISSUE THREAD

**Issue by iversond** [psadmin-io/psadmin-plus#91]
Add a hook system into `psadmin-plus` so that users can extend `psa` with custom actions for their domains. For example, after a domain is started, you may want to start a monitoring script and then kill the script before the domain is stopped.

* Add option for PRE/POST/REPLACE for each action
* Support multiple hooks per action
* Support for documenting steps in the `.psa.conf` or additional file:

```yaml
---
app:
  start: 
    pre:
      - /path/to/script.sh
      - /path/to/script2.rb
```
